### ISSUE TITLE
After installing updated Amazon Q plugin in Eclipse Amazon Q chat keeps showing an Authenticate button after submitting the chat command.

### ISSUE THREAD

**Issue by jridge-ezclocker** [aws/amazon-q-eclipse#450]
**Describe the bug**
After installing updated Amazon Q plugin in Eclipse Amazon Q chat keeps showing an Authenticate button after submitting the chat command. Clicking the Authenticate button seems to perform no action other than to hide the Authenticate button. Chat does not produce any results.

**To Reproduce**
1. Update Amazon Q plugin from previous release to current release 
2. Restart eclipse
3. Type a command in the Amazon Q chat - notice authenticate button appears.
4. Click authenticate, nothing appears to happen but authenticate button disappers.
5. Command is ignored and Amazon Q chat seems hung.

**Expected behavior**
Expecting Amazon Q to authenticate and report success or failure, and if success continue to execute the command.

**Screenshots**
Execute command shows authenticate button:

![Image](https://github.com/user-attachments/assets/c4f3e4e1-3e6f-4d20-b23a-11361ed0002f)

After clicking authenticate button:

![Image](https://github.com/user-attachments/assets/8d7b78ec-e1c7-4e48-9967-10a14c41256c)

**Your Environment:**
- OS: Windows 11
- Eclipse IDE for Java Developers (includes Incubating components)
- Version: 2025-03 (4.35.0)
- Build id: 20250306-0812
- Amazon Q for Eclipse, v2.0.0.202506051655, software.aws.toolkits.eclipse.amazonq.feature.feature.group
- JVM version: OpenJDK 11

**Comment by jridge-ezclocker** [comment]
Additional information:
Eclipse Error log shows the following error after clicking the Authenticate button:

**Comment by Noed** [comment]
same issue here, I can't logou on the plugin "...", need to restart eclipse to try to login again, but it fails

**Comment by shruti0085** [comment]
Hello @jridge-ezclocker , @Noed  we have released a new version 2.1.1 of the extension that contains some improvements in this space. Can you please upgrade and try this build?

**Comment by jridge-ezclocker** [comment]
> Thanks for reporting this issue. I have experienced something similar recently while attempting a chat prompted reauthenticate so I'll try to repro and get a fix in ASAP. Just to check - are you able to explicitly log out through the plugin's `...` menu and login again to work around this issue?

Logging out and back in results in the same problem. Doesn't resolve the issue.
